spring:
  cloud:
    function:
      definition: singleInputMultipleOutputs
    stream:
      bindings:
        singleInputMultipleOutputs-in-0:
          destination: author-extracted
          group: entity-selector
          concurrency: 1
        singleInputMultipleOutputs-out-0:
          destination: author-evaluation-passed
        singleInputMultipleOutputs-out-1:
          destination: author-evaluation-failed